### ISSUE TITLE
LDAP-167: DefaultDirContextValidator errors with default empty base

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-ldap#201]
["Marius Scurtescu":https://jira.spring.io/secure/ViewProfile.jspa?name=mariuss](Migrated from ["LDAP-167":https://jira.spring.io/browse/LDAP-167?redirect=false]) said:

Using a plain DefaultDirContextValidator results in errors, with both Active Directory and Sun Directory Server. As soon as a valid base DN is set it works as expected.

First a warning is logged:
14:05:50,355 WARN  [DefaultDirContextValidator] DirContext 'javax.naming.ldap.InitialLdapContext@799f9a' failed validation with an exception.
javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-031001A8, problem 2001 (NO_OBJECT), data 0, best match of:
    ''
]; remaining name ''
    at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3010)
    at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2931)
    at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2737)
    at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1808)
    at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1731)
    at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:368)
    at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:338)
    at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:321)
    at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:248)
    at org.springframework.ldap.pool.validation.DefaultDirContextValidator.validateDirContext(DefaultDirContextValidator.java:154)
    at org.springframework.ldap.pool.factory.DirContextPoolableObjectFactory.validateObject(DirContextPoolableObjectFactory.java:169)
    at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1035)
    at org.springframework.ldap.pool.factory.PoolingContextSource.getContext(PoolingContextSource.java:394)
    at org.springframework.ldap.pool.factory.PoolingContextSource.getReadOnlyContext(PoolingContextSource.java:374)
    at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:770)
    at org.springframework.ldap.core.LdapTemplate.lookup(LdapTemplate.java:897)
    [...]

then an error:
14:05:50,358 ERROR [SequentialChannelRunner] Channel run error!  Channel: channel1
org.springframework.dao.DataAccessResourceFailureException: Failed to borrow DirContext from pool.; nested exception is java.util.NoSuchElementException: Could not create a validated object
    at org.springframework.ldap.pool.factory.PoolingContextSource.getContext(PoolingContextSource.java:397)
    at org.springframework.ldap.pool.factory.PoolingContextSource.getReadOnlyContext(PoolingContextSource.java:374)
    at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:770)
    at org.springframework.ldap.core.LdapTemplate.lookup(LdapTemplate.java:897)
    [...]
Caused by: java.util.NoSuchElementException: Could not create a validated object
    at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1049)
    at org.springframework.ldap.pool.factory.PoolingContextSource.getContext(PoolingContextSource.java:394)
    ... 9 more

**Comment by spring-issuemaster** [comment]
This issue is related to #228
