### ISSUE TITLE
Getting exception on running Spring-Ldap-User-Admin-Sample- I build the example as mentioned in page "mvn jetty:run" then "mvn jetty:run -Dspring.profiles.active=no-apacheds -Dsample.ldap.url=ldaps://127.0.0.1:636 -Dsample.ldap.userDn=CN=ldaptest,CN=Users,DC=261consulting,DC=local -Dsample.ldap.password=secret -Dsample.ldap.base=ou=test,dc=261consulting,dc=local-Dsample.ldap.directory.type=AD" please let me know am i executing it in the right way. I am using maven to build

### ISSUE THREAD

**Issue by bhaskarAcharya** [spring-projects/spring-ldap#471]
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.config.EmbeddedValueResolver
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:430)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
        ... 49 more

**Comment by theiamdude** [comment]
I am having a similar issue, has anyone been able to solve this?

**Comment by rwinch** [comment]
Did you try using gradle instructions?
