### ISSUE TITLE
javax.naming.OperationNotSupportedException: [LDAP: error code 12 - Unavailable Critical Extension]; remaining name '/'

### ISSUE THREAD

**Issue by raunak** [spring-projects/spring-ldap#484]
I'm trying to connect to "Oracle Directory Server Enterprise Edition platform" using Spring LDAP. When I run code against the server, I get the following exception:
`javax.naming.OperationNotSupportedException: [LDAP: error code 12 - Unavailable Critical Extension]; remaining name '/'
	at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3214)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
	at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1846)
	at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1769)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
	at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:276)
	at org.springframework.ldap.core.LdapTemplate$3.executeSearch(LdapTemplate.java:303)
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:363)
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:309)
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:642)
	at com.scanner.LDAPScanner.start(PeopleScanner.java:123)`

I'm very confused why this is being thrown. What extension is the stack trace referring to?

**Comment by raunak** [comment]
After much debugging, I realised the error is caused because the LDAP server does not support PagedResultControl. After I removed it, I was able to get up to 1000 results.

**Comment by sharpedavid** [comment]
> After much debugging, I realised the error is caused because the LDAP server does not support PagedResultControl. After I removed it, I was able to get up to 1000 results.

Thanks. I encountered the same error when trying to integrate Keycloak with "Sun-ONE-Directory/5.2" by "Sun Microsystems, Inc.", a really old LDAP server. Turning off Pagination resolved the issue.

` javax.naming.OperationNotSupportedException: [LDAP: error code 12 - Unavailable Critical Extension]; remaining name 'o=hnet,st=bc,c=ca'`
