### ISSUE TITLE
using ODM update memberOf error:  value #0 already exists

### ISSUE THREAD

**Issue by huashiyiqike** [spring-projects/spring-ldap#541]
Hi, I am puzzled by the updating rules in ODM. I don't know if it is a bug or did I used the wrong configuration.

My ODM definition class:

@Entry(objectClasses = {"inetOrgPerson"},base="ou=users")
final public class Person { 
...
@Attribute(name="memberOf")
    private ArrayList<String> memberOf;  

public ArrayList<String> getMemberOf() {
        return memberOf;
    }

    public Person setMemberOf(ArrayList<String> memberOf) {
        this.memberOf = memberOf;
        return this;
    }
}
when I  updated Person a while a is a member of three groups, although I did not change the value of the groups, it was judged to update and has the following error

```

javax.naming.directory.AttributeInUseException: [LDAP: error code 20 - modify/add: memberOf: value #0 already exists]
	at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3142) ~[na:na]
	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3104) ~[na:na]
	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2895) ~[na:na]
	at java.naming/com.sun.jndi.ldap.LdapCtx.c_modifyAttributes(LdapCtx.java:1476) ~[na:na]
	at java.naming/com.sun.jndi.toolkit.ctx.ComponentDirContext.p_modifyAttributes(ComponentDirContext.java:277) ~[na:na]
	at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.modifyAttributes(PartialCompositeDirContext.java:192) ~[na:na]
	at java.naming/javax.naming.directory.InitialDirContext.modifyAttributes(InitialDirContext.java:172) ~[na:na]
	at org.springframework.ldap.core.LdapTemplate$19.executeWithContext(LdapTemplate.java:966) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:817) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.executeReadWrite(LdapTemplate.java:812) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.modifyAttributes(LdapTemplate.java:964) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.modifyAttributes(LdapTemplate.java:1317) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.update(LdapTemplate.java:1778) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at server.service.UserService.update(UserService.java:36) ~[main/:na]
```
Thanks in advance

**Comment by huashiyiqike** [comment]
I did some digging

In file DirContextAdapter.java,  private final NameAwareAttributes originalAttrs does not contain attribute memberOf, so collectModifications will think memberOf is changed even actually not.
Is it designed to be so?

private void collectModifications(NameAwareAttribute changedAttr,
			List<ModificationItem> modificationList) throws NamingException {
		NameAwareAttribute currentAttribute = originalAttrs.get(changedAttr.getID());

**Comment by huashiyiqike** [comment]
I got it now: should be changed in group class, not user class.

**Comment by anthony-o** [comment]
I have the same problem while updating a `User` on which I have `@Attribute(name="memberOf") private Set<Name> groups = new HashSet<>();` : I first load it by using `userRepository.findOneByEmail` and then save it after a modification on another attribute than the "groups" and obtain `org.springframework.ldap.AttributeInUseException: [LDAP: error code 20 - modify/add: memberOf: value #0 already exists]; nested exception is javax.naming.directory.AttributeInUseException: [LDAP: error code 20 - modify/add: memberOf: value #0 already exists]`.

After digging, it seems that `org.springframework.ldap.core.LdapTemplate#update` does first a `org.springframework.ldap.core.LdapTemplate#lookupContext(javax.naming.Name)` which passes null attributes in order to obtain all from LDAP, and LDAP does not return `memberof` attributes, so later when `org.springframework.ldap.core.LdapTemplate#modifyAttributes(org.springframework.ldap.core.DirContextOperations)` it detects a modification on the field...

@huashiyiqike how did you manage to pass through this problem?
