### ISSUE TITLE
lookup with baseDn configured is problematic

### ISSUE THREAD

**Issue by davinkevin** [spring-projects/spring-ldap#542]
Hi, 

I'm facing the same issue described in this [SO](https://stackoverflow.com/questions/55285743/spring-ldaptemplate-how-to-lookup-fully-qualified-dn-with-configured-base-dn) question. 

My use case is the following, I am fetching some groups by `query()` and then I try to do a lookup on each `member` of this group. 

My configuration and code look like that (I can't share the project 😓): 

application.yml:
```yml
spring.ldap:
  username: foo
  password: bar
  base: OU=baz,DC=example,DC=corp
```

Code simply fetching groups: 
```kotlin
fun findGroups(): List<LDAPGroup> =
       ldapTemplate
            .search(groupQuery, simpleGroupAttributeMapper)
            .filterNotNull()
            .map { LDAPGroup(it) }

private val groupQuery = query()
        .attributes("cn", "member")
        .where("objectClass").`is`("group")

private val simpleGroupAttributeMapper = AttributesMapper { it["cn"]?.get()?.toString() }
```

All works fine for this, but If I want to fetch members of groups:

```kotlin
fun findLinkBetweenUserAndGroup(): List<LDAPLinkUserToGroup> {
        return ldapTemplate.search(groupQuery, groupToUserAttributesMapper)
                .filterNotNull()
                .flatMap { (cn, members) -> members
                        .mapNotNull { member -> ldap.lookup(member, ldapUserMapper) }
                        .map { user -> LDAPLinkUserToGroup(user.email, cn) }
                }
                .toList()
    }

private val groupToUserAttributesMapper = AttributesMapper {
    val cn = it["cn"]?.get()?.toString() ?: return@AttributesMapper null
    val members = (it["member"] ?: return@AttributesMapper null)
            .all
            .asSequence()
            .map { v -> v.toString() }
            .toList()

    cn to members
}
```

This codes ends up on error because `lookup` add the `base-dn` to the value given as paremeter... which already includes the `base-dn`, because this is extracted from a field of the Active Directory. 

So, I have the following error when executing this:
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:783) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:764) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at com.gitlab.davinkevin.spring.ldap.issue.LdapAccountSynchApplicationKt.main(LdapAccountSynchApplication.kt:13) ~[classes/:na]
Caused by: org.springframework.ldap.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:
	'OU=baz,DC=example,DC=corp'
]; nested exception is javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:
	'OU=baz,DC=example,DC=corp'
]; remaining name 'CN=loic name,OU=Users,OU=Internal,OU=baz,DC=example,DC=corp'
	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:183) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:820) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:803) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.lookup(LdapTemplate.java:870) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at com.gitlab.davinkevin.spring.ldap.issue.ldap.LDAPService.findLinkBetweenUserAndGroup(LDAPService.kt:28) ~[classes/:na]
	at com.gitlab.davinkevin.spring.ldap.issue.ldap.LDAPConfiguration$clr$1.run(LDAPConfiguration.kt:16) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:780) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	... 5 common frames omitted
Caused by: javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:
	'OU=baz,DC=example,DC=corp'
	]
	at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3183) ~[na:na]
	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3104) ~[na:na]
	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2895) ~[na:na]
	at java.naming/com.sun.jndi.ldap.LdapCtx.c_getAttributes(LdapCtx.java:1330) ~[na:na]
	at java.naming/com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:235) ~[na:na]
	at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:141) ~[na:na]
	at java.naming/com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:129) ~[na:na]
	at java.naming/javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:142) ~[na:na]
	at java.naming/javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:137) ~[na:na]
	at org.springframework.ldap.core.LdapTemplate$12.executeWithContext(LdapTemplate.java:872) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:817) ~[spring-ldap-core-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	... 10 common frames omitted
```

Is it possible to configure `lookup` operation to ignore configured `dn` ? In my case, I rely on string manipulation in order to remove the `base-dn` configured from the value found in the field `member`... which not seems to be a clean way to do it.

**Comment by jarulraj666** [comment]
I am too facing same issue. Can someone help on this?

**Comment by rwinch** [comment]
If you can provide a complete but minimal sample, you are much more likely to be able to get help because it reduces the effort for anyone that might be able to troubleshoot the issue.

**Comment by davinkevin** [comment]
I understand, but doing a setup when using an ldap is a bit difficult. 

By the way, this can be reproduced in unit tests of the project. Here we can't do a `lookup` call on user resulting from a `search` on group becaue the `base-dn` field is added.

**Comment by rwinch** [comment]
It sounds like you can use an in memory ldap instance then?

**Comment by jzheaux** [comment]
Thanks, @davinkevin, I've commented on the linked SO question. We can continue the conversation over there, if needed.
