### ISSUE TITLE
ldapSearch doesn't work after password is changed.

### ISSUE THREAD

**Issue by Staticsubh** [spring-projects/spring-ldap#564]
ldap search gives the below exception when a user's password is changed.

```
org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903D3, comment: AcceptSecurityContext error, data 52e, v3839 ]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903D3, comment: AcceptSecurityContext error, data 52e, v3839 ]
	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:191)
	at org.springframework.ldap.core.support.AbstractContextSource.createContext(AbstractContextSource.java:355)
	at org.springframework.ldap.core.support.AbstractContextSource.doGetContext(AbstractContextSource.java:139)
	at org.springframework.ldap.core.support.AbstractContextSource.getReadOnlyContext(AbstractContextSource.java:158)
	at org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:357)
```
We are using the below method to get the data from LDAP.

`String filter = String.format(query, userName);
result = ldapTemplate.search("", filter, new LdapEntryIdentificationContextMapper());`

Attaching the logs.
[server.log.Default.CentricityPractice_failure.txt](https://github.com/spring-projects/spring-ldap/files/5150527/server.log.Default.CentricityPractice_failure.txt)

**Comment by erdbeerschnitzel** [comment]
I also had some of these errors but it always was related to a caching issue in the Active Directory server forest and resolved automatically after some time.

Can you confirm that this problem still occurs 1 or 2 hours after changing the password?

**Comment by Staticsubh** [comment]
Yes it was a cache related issue. You can use ldp.exe to investigate further.
